version: "3"

services:
  queue_ms:
    restart: always
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 3000
      RABBITMQ_URI: amqp://user:pass@host.docker.internal:10001
      FILE_MS_URI: host.docker.internal:3131
    ports:
      - 20001:3000
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.12.13-management-alpine
    restart: always
    ports:
      - 10001:5672
      - 10011:15672
    volumes:
      - queue_ms_rabbitmq_volume:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass

volumes:
  queue_ms_volume:
  queue_ms_rabbitmq_volume:
